<?php

/**
 * ProcessWire Page List Select Multiple Inputfield module
 *
 * A Page List Selector for selecting multiple pages
 *
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class InputfieldChosenSelect extends InputfieldSelectMultiple implements InputfieldHasArrayValue{

	protected $chosenOptions = array();

	public static function getModuleInfo() {
		return array(
			'title' => __('Chosen Select', __FILE__), // Module Title
			'summary' => __('Selection of multiple pages from a ProcessWire page tree list', __FILE__), // Module Summary
			'version' => 100, 
			);
	}

	public function init() {
		parent::init();
		wire('modules')->get('JqueryCore'); // required by jQuery UI
		wire('modules')->get('JqueryUI');

		$this->setChosenOption('width', "100%");
	}

	public function setChosenOption($key, $value) {
		$this->chosenOptions[$key] = $value; 
	}

	public function ___render() {
		$class = $this->className(); 
		$info = self::getModuleInfo();
		$ver = $info['version'];

		$this->config->scripts->add($this->config->urls->$class . "chosen/chosen.jquery.min.js?v=$ver");
		$this->config->styles->add($this->config->urls->$class . "chosen/chosen.min.css?v=$ver");

		$this->config->js($this->id, $this->chosenOptions);

		return parent::___render();
	}

	public function ___install() {
		$data = $this->modules->getModuleConfigData("InputfieldPage");
		array_push($data["inputfieldClasses"], $this->className());
		$this->modules->saveModuleConfigData("InputfieldPage", $data);
	}

	public function ___uninstall() {
		$fields = wire('fields')->find("type=FieldtypePage");

		foreach($fields as $field){
			if($field->inputfield !== $this->className()) $fields->remove($field);
		}

		$this->warning($this->className()." was used in following fields: ".$fields->implode(", ", "name"));

		$data = $this->modules->getModuleConfigData("InputfieldPage");

		if(in_array($this->className(), $data["inputfieldClasses"])){
			$key = array_search($this->className(), $data["inputfieldClasses"]);
			unset($data["inputfieldClasses"][$key]);

			$this->modules->saveModuleConfigData("InputfieldPage", $data);
		}
	}
	
}
